name = "hex-graph-iso-mathlib"
defaultTargets = ["HexGraphIsoMathlib"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexGraphIso"
git = "https://github.com/leanprover/hex-graph-iso.git"
rev = "17e07ae91a9a660a12a4c173e916fc2386aa1ce6"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.34.0-rc2"

[[lean_lib]]
name = "HexGraphIsoMathlib"

[[lean_lib]]
name = "HexGraphIsoMathlibTests"
globs = ["HexGraphIsoMathlib.TacticTests"]
