/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexGraphIsoMathlib.Encode
public import Mathlib.GroupTheory.GroupAction.Quotient
public import Mathlib.Data.Fintype.Perm
import all HexGraphIso.Generated

public section

namespace Hex.GraphIso

variable {n k : Nat}

instance : Group (Perm n) where
  mul := Perm.comp
  one := Perm.id n
  inv := Perm.inv
  mul_assoc := Perm.comp_assoc
  one_mul := Perm.id_comp
  mul_one := Perm.comp_id
  inv_mul_cancel := Perm.inv_comp_self

@[simp] theorem Perm.mul_get (p q : Perm n) (v : Fin n) :
    (p * q).get v = p.get (q.get v) := Perm.get_comp p q v

@[simp] theorem Perm.one_get (v : Fin n) : (1 : Perm n).get v = v := Perm.get_id v

noncomputable instance : Fintype (Perm n) :=
  Fintype.ofInjective Perm.toEquiv (fun _p _q h => Perm.ext (fun i => congrArg (fun e => e i) h))

instance : MulAction (Perm n) (Fin n) where
  smul := Perm.get
  one_smul := Perm.get_id
  mul_smul := Perm.get_comp

/-- The full colour-preserving automorphism group, as a subgroup of the
executable permutations. -/
@[expose] def Aut.group (G : Colored n k) : Subgroup (Perm n) where
  carrier := {p | IsIso G G p}
  one_mem' := IsIso.refl G
  mul_mem' hp hq := hq.trans hp
  inv_mem' hp := hp.symm

@[simp] theorem Aut.mem_group (G : Colored n k) (p : Perm n) :
    p ∈ Aut.group G ↔ IsIso G G p := Iff.rfl

/-- The subgroup generated by the returned list is the full automorphism group. -/
theorem Aut.closure_eq_group (G : Colored n k) :
    Subgroup.closure {p | p ∈ Aut.gens G} = Aut.group G := by
  apply le_antisymm
  · apply (Subgroup.closure_le _).mpr
    exact fun _ hp => Aut.gens_isIso hp
  · intro p hp
    have h := Aut.complete G hp
    exact h.induction (Subgroup.one_mem _) (fun _ hm => Subgroup.subset_closure hm)
      (fun _ _ hp hq => Subgroup.mul_mem _ hp hq) (fun _ hp => Subgroup.inv_mem _ hp)

/-- The group-action orbit relation is the executable graph's automorphism orbit relation. -/
theorem Aut.mem_orbit (G : Colored n k) (u v : Fin n) :
    v ∈ MulAction.orbit (Aut.group G) u ↔ SameOrbit G u v := by
  constructor
  · rintro ⟨p, hp⟩
    exact SameOrbit.intro p.val p.property hp
  · intro h
    obtain ⟨p, hp, hv⟩ := h.elim
    exact ⟨⟨p, hp⟩, hv⟩

end Hex.GraphIso
