/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/
module

public import HexGraphIsoMathlib.Sparse.AutGroup
public import HexGraphIsoMathlib.Sparse.Order
public import HexGraphIsoMathlib.Sparse.Encode
public import HexGraphIsoMathlib.Automorphism
import all HexGraphIsoMathlib.Sparse.Encode
import all HexGraphIsoMathlib.Encode
import all HexGraphIsoMathlib.Basic
import all HexGraphIsoMathlib.Sparse.AutGroup
import all HexGraphIso.Sparse.Autos
import all HexGraphIso.Generated

public section

namespace Hex.GraphIso.Mathlib.Sparse

universe u
variable {V : Type u} [Fintype V] {n k : Nat}

/-- Decode the complete native sparse generator list into Mathlib
colour-preserving automorphisms, retaining its order and every entry. -/
def autos (e : V ≃ Fin n) (G : Mathlib.Colored V k) [DecidableRel G.graph.Adj] :
    List (Mathlib.Colored.Iso G G) :=
  (GraphIso.Sparse.Aut.gens (encode e G)).attach.map fun p =>
    isoOfIsIso e e (GraphIso.Sparse.Aut.gens_isIso p.property)

/-- The orbit count computed by the native sparse search. -/
def autNumOrbits (e : V ≃ Fin n) (G : Mathlib.Colored V k) [DecidableRel G.graph.Adj] : Nat :=
  GraphIso.Sparse.Aut.numOrbits (encode e G)

/-- The first-path index product computed by one native sparse search. -/
def autOrder (e : V ≃ Fin n) (G : Mathlib.Colored V k) [DecidableRel G.graph.Adj] : Nat :=
  GraphIso.Sparse.Aut.order (encode e G)

/-- Native sparse encoding identifies the full automorphism groups. -/
def autEquiv (e : V ≃ Fin n) (G : Mathlib.Colored V k) [DecidableRel G.graph.Adj] :
    Mathlib.Colored.Iso G G ≃* GraphIso.Sparse.Aut.group (encode e G) where
  toFun f := ⟨Perm.ofEquiv (e.symm.trans (f.graphIso.toEquiv.trans e)),
    (GraphIso.Sparse.Aut.mem_group _ _).mpr (isIso_of_iso e e f)⟩
  invFun p := isoOfIsIso e e ((GraphIso.Sparse.Aut.mem_group _ _).mp p.property)
  left_inv f := by
    apply Mathlib.Colored.Iso.ext
    intro v
    change e.symm ((Perm.ofEquiv (e.symm.trans (f.graphIso.toEquiv.trans e))).get (e v)) = f.graphIso v
    simp only [Perm.get_ofEquiv, Equiv.trans_apply, Equiv.symm_apply_apply]
    rfl
  right_inv p := by
    apply Subtype.ext
    apply Perm.ext
    intro v
    simp only [Perm.get_ofEquiv, Equiv.trans_apply, isoOfIsIso, Mathlib.isoOfIsIso,
      decodePerm_apply, Equiv.apply_symm_apply]
  map_mul' f g := by
    apply Subtype.ext
    apply Perm.ext
    intro v
    change (Perm.ofEquiv (e.symm.trans ((f * g).graphIso.toEquiv.trans e))).get v =
      ((Perm.ofEquiv (e.symm.trans (f.graphIso.toEquiv.trans e))) *
        (Perm.ofEquiv (e.symm.trans (g.graphIso.toEquiv.trans e)))).get v
    simp only [Perm.mul_get, Perm.get_ofEquiv, Equiv.trans_apply]
    change e (f.graphIso (g.graphIso (e.symm v))) = e (f.graphIso (e.symm (e (g.graphIso (e.symm v)))))
    rw [Equiv.symm_apply_apply]

/-- Every Mathlib colour-preserving automorphism is generated by the
decoded output of the native sparse traversal. -/
theorem autos_complete (e : V ≃ Fin n) (G : Mathlib.Colored V k) [DecidableRel G.graph.Adj]
    (f : Mathlib.Colored.Iso G G) : f ∈ Subgroup.closure {g | g ∈ autos e G} := by
  let H := encode e G
  let C := Subgroup.closure {g | g ∈ autos e G}
  have hdecode (p : Perm n) (hp : Perm.Generated (GraphIso.Sparse.Aut.gens H) p) :
      ∀ hi : GraphIso.Sparse.IsIso H H p,
        (autEquiv e G).symm ⟨p, (GraphIso.Sparse.Aut.mem_group H p).mpr hi⟩ ∈ C := by
    induction hp with
    | id =>
      intro hi
      change (autEquiv e G).symm (1 : GraphIso.Sparse.Aut.group H) ∈ C
      rw [map_one]
      exact C.one_mem
    | @mem p hm =>
      intro hi
      apply Subgroup.subset_closure
      change isoOfIsIso e e hi ∈ (GraphIso.Sparse.Aut.gens H).attach.map _
      exact List.mem_map.mpr ⟨⟨p, hm⟩, List.mem_attach _ _, rfl⟩
    | @comp p q hp hq ihp ihq =>
      intro hi
      have hip := (GraphIso.Sparse.Aut.generated_iff H p).mp hp
      have hiq := (GraphIso.Sparse.Aut.generated_iff H q).mp hq
      have he : (⟨p.comp q, (GraphIso.Sparse.Aut.mem_group H _).mpr hi⟩ : GraphIso.Sparse.Aut.group H) =
          ⟨p, (GraphIso.Sparse.Aut.mem_group H _).mpr hip⟩ *
            ⟨q, (GraphIso.Sparse.Aut.mem_group H _).mpr hiq⟩ := Subtype.ext rfl
      rw [he, map_mul]
      exact C.mul_mem (ihp hip) (ihq hiq)
    | @inv p hp ih =>
      intro hi
      have hip := (GraphIso.Sparse.Aut.generated_iff H p).mp hp
      have he : (⟨p.inv, (GraphIso.Sparse.Aut.mem_group H _).mpr hi⟩ : GraphIso.Sparse.Aut.group H) =
          (⟨p, (GraphIso.Sparse.Aut.mem_group H _).mpr hip⟩ : GraphIso.Sparse.Aut.group H)⁻¹ := Subtype.ext rfl
      rw [he, map_inv]
      exact C.inv_mem (ih hip)
  have hf : GraphIso.Sparse.IsIso H H (autEquiv e G f).val :=
    (GraphIso.Sparse.Aut.mem_group H _).mp (autEquiv e G f).property
  simpa using hdecode _ (GraphIso.Sparse.Aut.complete H hf) hf

/-- The actual sparse representative array classifies the full Mathlib
automorphism orbits for any finite enumeration. -/
theorem autos_sameOrbit (e : V ≃ Fin n) (G : Mathlib.Colored V k) [DecidableRel G.graph.Adj]
    (v w : V) :
    (GraphIso.Sparse.Aut.orbits (encode e G))[(e v).val]! =
        (GraphIso.Sparse.Aut.orbits (encode e G))[(e w).val]! ↔
      ∃ f : Mathlib.Colored.Iso G G, f.graphIso v = w := by
  rw [GraphIso.Sparse.Aut.orbits_eq_iff_sameOrbit]
  constructor
  · rintro ⟨p, hp, he⟩
    refine ⟨isoOfIsIso e e hp, ?_⟩
    change e.symm (p.get (e v)) = w
    rw [he, Equiv.symm_apply_apply]
  · rintro ⟨f, hf⟩
    refine ⟨_, isIso_of_iso e e f, ?_⟩
    simp only [Perm.get_ofEquiv, Equiv.trans_apply, Equiv.symm_apply_apply]
    change e (f.graphIso v) = e w
    rw [hf]

noncomputable def autOrbitEquiv (e : V ≃ Fin n) (G : Mathlib.Colored V k) [DecidableRel G.graph.Adj] :
    MulAction.orbitRel.Quotient (Mathlib.Colored.Iso G G) V ≃
      MulAction.orbitRel.Quotient (GraphIso.Sparse.Aut.group (encode e G)) (Fin n) :=
  Quotient.congr e fun v w => by
    rw [MulAction.orbitRel_apply, MulAction.orbitRel_apply, GraphIso.Sparse.Aut.mem_orbit,
      ← GraphIso.Sparse.Aut.orbits_eq_iff_sameOrbit, autos_sameOrbit]
    rfl

/-- The native sparse orbit count equals the number of full Mathlib
automorphism orbits, including empty graphs and arbitrary enumerations. -/
theorem autNumOrbits_card (e : V ≃ Fin n) (G : Mathlib.Colored V k) [DecidableRel G.graph.Adj] :
    autNumOrbits e G = Nat.card (MulAction.orbitRel.Quotient (Mathlib.Colored.Iso G G) V) :=
  (GraphIso.Sparse.Aut.numOrbits_card (encode e G)).trans (Nat.card_congr (autOrbitEquiv e G)).symm

/-- The product accumulated by the native sparse traversal is the order
of the full Mathlib automorphism group for any chosen enumeration. -/
theorem autOrder_card (e : V ≃ Fin n) (G : Mathlib.Colored V k) [DecidableRel G.graph.Adj] :
    autOrder e G = Nat.card (Mathlib.Colored.Iso G G) :=
  (GraphIso.Sparse.Aut.order_card (encode e G)).trans (Nat.card_congr (autEquiv e G).toEquiv).symm

end Hex.GraphIso.Mathlib.Sparse
